//! Lookup tables, generated by `build.rs` from `tables/*.csv` into `OUT_DIR` and
//! included here. They never exist in the source tree, so they cannot drift from the CSVs.
//!
//! Lookups resolve in three tiers, cheapest first:
//!
//! 1. **Arithmetic** — digits, `a-z`/`A-Z`, `а-я`/`А-Я`/`ё`/`Ё` are contiguous in both
//!    Unicode and CL-8, so codes are computed. Over 95% of text, no memory touched.
//! 2. **Range rejection** — one comparison discards everything outside the tables:
//!    CJK, emoji, Arabic, and every other unsupported script.
//! 3. **Binary search** over a sorted index of one-byte row numbers, not a second
//!    copy of the codepoints.

include!(concat!(env!("OUT_DIR"), "/tables.rs"));

use crate::consts::MODIFIER_FIRST;

/// Codepoint for a CL-8 code, or `None` for the reserved 226..=231 and controls.
#[must_use]
#[inline]
pub fn codepoint_of(code: u8) -> Option<u32> {
    BASE_TABLE.get(code as usize).copied().map(u32::from)
}

/// CL-8 code for a codepoint: arithmetic for the common alphabets, otherwise a
/// range check and a binary search over [`BASE_BY_CP`].
#[must_use]
#[inline]
#[allow(clippy::cast_possible_truncation)]
pub fn code_of(codepoint: u32) -> Option<u8> {
    match codepoint {
        0x0030..=0x0039 => return Some((codepoint - 0x0030) as u8),
        0x0061..=0x007A => return Some((codepoint - 0x0061 + 10) as u8),
        0x0430..=0x044F => {
            let offset = codepoint - 0x0430;
            // Code 42 is reserved for `ё`, which sits outside the а..я block.
            return Some(if offset < 6 {
                (36 + offset) as u8
            } else {
                (36 + offset + 1) as u8
            });
        }
        0x0451 => return Some(42),
        0x0041..=0x005A => return Some((codepoint - 0x0041 + 161) as u8),
        0x0410..=0x042F => {
            let offset = codepoint - 0x0410;
            // Code 193 is reserved for `Ё`, mirroring the lowercase layout.
            return Some(if offset < 6 {
                (187 + offset) as u8
            } else {
                (187 + offset + 1) as u8
            });
        }
        0x0401 => return Some(193),
        _ => {}
    }

    code_of_indexed(codepoint)
}

/// Index path of [`code_of`]: punctuation, symbols, supplementary Cyrillic.
///
/// Out of line on purpose — inlining the search makes `code_of` too large to fold
/// into its callers, and the arithmetic path pays for it.
#[inline(never)]
fn code_of_indexed(codepoint: u32) -> Option<u8> {
    // Nothing above the table's largest codepoint can be present.
    let Ok(needle) = u16::try_from(codepoint) else {
        return None;
    };
    if needle > BASE_CP_MAX {
        return None;
    }

    // `BASE_BY_CP` holds codes; the codepoint is read back through `BASE_TABLE`.
    let mut lo = 0usize;
    let mut hi = BASE_BY_CP.len();
    while lo < hi {
        let mid = lo + (hi - lo) / 2;
        let code = BASE_BY_CP[mid];
        match BASE_TABLE[code as usize].cmp(&needle) {
            core::cmp::Ordering::Equal => return Some(code),
            core::cmp::Ordering::Less => lo = mid + 1,
            core::cmp::Ordering::Greater => hi = mid,
        }
    }
    None
}

/// Applies a diacritic to a base code, or `None` if the pair is undefined.
///
/// Each modifier owns a contiguous base-sorted slice of [`MODIFIER_TABLE`] delimited
/// by [`MOD_OFFSETS`], so the search narrows to about fifteen rows.
#[must_use]
#[inline]
pub fn apply_modifier(modifier: Modifier, base: u8) -> Option<u32> {
    let group = (modifier as u8).wrapping_sub(MODIFIER_FIRST) as usize;
    if group + 1 >= MOD_OFFSETS.len() {
        return None;
    }
    let mut lo = MOD_OFFSETS[group] as usize;
    let mut hi = MOD_OFFSETS[group + 1] as usize;
    while lo < hi {
        let mid = lo + (hi - lo) / 2;
        let (_, b, result) = MODIFIER_TABLE[mid];
        match b.cmp(&base) {
            core::cmp::Ordering::Equal => return Some(u32::from(result)),
            core::cmp::Ordering::Less => lo = mid + 1,
            core::cmp::Ordering::Greater => hi = mid,
        }
    }
    None
}

/// Uppercase form of a codepoint, or `None` for digits, punctuation and symbols.
///
/// `-0x20` for `a..z` and `а..я`, otherwise a binary search over the exceptions.
#[must_use]
#[inline]
pub fn to_upper(codepoint: u32) -> Option<u32> {
    if matches!(codepoint, 0x0061..=0x007A | 0x0430..=0x044F) {
        return Some(codepoint - 0x20);
    }
    if codepoint == 0x0451 {
        return Some(0x0401);
    }
    let needle = u16::try_from(codepoint).ok()?;
    let mut lo = 0usize;
    let mut hi = CAPITALIZE_TABLE.len();
    while lo < hi {
        let mid = lo + (hi - lo) / 2;
        let (lower, upper) = CAPITALIZE_TABLE[mid];
        match lower.cmp(&needle) {
            core::cmp::Ordering::Equal => return Some(u32::from(upper)),
            core::cmp::Ordering::Less => lo = mid + 1,
            core::cmp::Ordering::Greater => hi = mid,
        }
    }
    None
}

/// The `(Modifier, base_code)` pair producing a composite codepoint.
///
/// One comparison rejects anything outside the range of composite results.
#[must_use]
#[inline]
pub fn find_modifier_pair_for_codepoint(codepoint: u32) -> Option<(Modifier, u8)> {
    let Ok(needle) = u16::try_from(codepoint) else {
        return None;
    };
    if !(MOD_RESULT_MIN..=MOD_RESULT_MAX).contains(&needle) {
        return None;
    }
    let mut lo = 0usize;
    let mut hi = MOD_BY_RESULT.len();
    while lo < hi {
        let mid = lo + (hi - lo) / 2;
        let (modifier, base, result) = MODIFIER_TABLE[MOD_BY_RESULT[mid] as usize];
        match result.cmp(&needle) {
            core::cmp::Ordering::Equal => return Some((modifier, base)),
            core::cmp::Ordering::Less => lo = mid + 1,
            core::cmp::Ordering::Greater => hi = mid,
        }
    }
    None
}

/// Lowercase form of an uppercase codepoint, or `None` if it has none.
///
/// `+0x20` for `A..Z` and `А..Я`, then a binary search over the exceptions.
#[must_use]
#[inline]
pub fn from_upper_to_lower(codepoint: u32) -> Option<u32> {
    if matches!(codepoint, 0x0041..=0x005A | 0x0410..=0x042F) {
        return Some(codepoint + 0x20);
    }
    if codepoint == 0x0401 {
        return Some(0x0451);
    }
    if codepoint == 0x0130 {
        return Some(0x0069);
    }

    let needle = u16::try_from(codepoint).ok()?;
    let mut lo = 0usize;
    let mut hi = REVERSE_CAPITALIZE_TABLE.len();
    while lo < hi {
        let mid = lo + (hi - lo) / 2;
        let (upper, lower) = REVERSE_CAPITALIZE_TABLE[mid];
        match upper.cmp(&needle) {
            core::cmp::Ordering::Equal => return Some(u32::from(lower)),
            core::cmp::Ordering::Less => lo = mid + 1,
            core::cmp::Ordering::Greater => hi = mid,
        }
    }
    None
}
